import {
  countDiffAnchors,
  parseCombinedResponse,
  parseDescriptionOnlyResponse,
  parseTitleOnlyResponse,
} from "../src/background/parse";
import { expectExcludes, expectIncludes, expectMatch, getFailures } from "./expect-helpers";
import { K8S_TEMPLATE } from "./fixtures";

function testCodeRabbitBlock(): void {
  const input =
    "## Summary\nFixed the token expiry bug.\n\n## Summary by CodeRabbit\n\n- **Bug Fixes**: token refresh\n- **Documentation**: updated docs\n\nGenerated by CodeRabbit";
  const out = parseDescriptionOnlyResponse(input);
  expectExcludes("CodeRabbit heading removed", out, "CodeRabbit");
  expectExcludes("category bullets removed", out, "**Bug Fixes**");
  expectExcludes("docs category bullet removed", out, "**Documentation**");
  expectIncludes("authored summary kept", out, "Fixed the token expiry bug.");
  expectExcludes("generated-by footer removed", out, "Generated by");
}

function testCubicAndMarkers(): void {
  const input =
    "## Changes\nDid the thing.\n\n## Summary by cubic\n- item\n<!-- copyberry-projection-id 123 -->\n[![badge](https://img.shields.io/x.svg)](https://example.com)";
  const out = parseDescriptionOnlyResponse(input);
  expectExcludes("cubic heading removed", out, "cubic");
  expectExcludes("copyberry marker removed", out, "copyberry");
  expectExcludes("badge line removed", out, "img.shields.io");
  expectIncludes("real section kept", out, "Did the thing.");
}

function testTemplatePreservation(): void {
  const out = parseDescriptionOnlyResponse(K8S_TEMPLATE);
  expectMatch("kubernetes template preserved byte-for-byte", out, K8S_TEMPLATE.trim());
}

function testTemplateWithBotAppendix(): void {
  const input = K8S_TEMPLATE + "\n## Summary by CodeRabbit\n- stuff\n";
  const out = parseDescriptionOnlyResponse(input);
  expectIncludes("template blocks survive", out, "<!-- tell us why; keep it short -->");
  expectIncludes("checkboxes survive", out, "- [ ] Tests added");
  expectExcludes("bot appendix removed", out, "CodeRabbit");
}

function testRubberStampChecklist(): void {
  const plain = "Did the work.\n\n- [x] I tested my changes thoroughly\n- [x] Works on my machine";
  const out = parseDescriptionOnlyResponse(plain);
  expectExcludes("stamped checklist lines removed", out, "I tested my changes");
  const templateBody = "## Checklist\nSome explanation.\n\n- [x] I tested my changes";
  expectIncludes("template checklist kept", parseDescriptionOnlyResponse(templateBody), "I tested my changes");
}

function testCombinedParse(): void {
  const input = "fix: resolve token expiry\n\n## Summary\nFixed it.\n\nAutomated Code Change";
  const out = parseCombinedResponse(input);
  expectMatch("combined title parsed", out.title, "fix: resolve token expiry");
  expectExcludes("combined description cleaned", out.description, "Automated Code Change");
  expectIncludes("combined description kept", out.description, "Fixed it.");
}

function testCopilotTrailers(): void {
  const input =
    "## Summary\nReal work.\n\nCo-Authored-By: Copilot <223556219+Copilot@users.noreply.github.com>\nCo-Authored-By: Jane Doe <jane@example.com>";
  const out = parseDescriptionOnlyResponse(input);
  expectExcludes("bot co-author trailer removed", out, "Copilot");
  expectIncludes("human co-author trailer kept", out, "Jane Doe");
}

function testAnchorGuard(): void {
  expectMatch("counts anchor links", countDiffAnchors("a [[1]](diffhunk://x) b [[2]](diffhunk://y)"), 2);
  expectMatch("zero anchors detected", countDiffAnchors("plain text with no links"), 0);
  const withAnchors = parseDescriptionOnlyResponse("`a.ts` — fixed [[1]](diffhunk://#diff-aaaa_L1-R2)", {
    expectAnchors: true,
  });
  expectIncludes("expected anchors survive parsing", withAnchors, "diffhunk://");
  // expectAnchors only warns (via logMsg) — output is never rewritten
  const withoutAnchors = parseDescriptionOnlyResponse("plain body, no links", { expectAnchors: true });
  expectMatch("warning path never mutates output", withoutAnchors, "plain body, no links");
  const pseudoTitle = parseDescriptionOnlyResponse("Overview: did the thing\n\n## Details\nbody");
  expectMatch("short pseudo-title line still stripped", pseudoTitle, "## Details\nbody");
  const anchoredFirst = parseDescriptionOnlyResponse("`a.ts` — fixed [[1]](diffhunk://#diff-aaaa_L1-R2)");
  expectIncludes("anchored first line survives", anchoredFirst, "diffhunk://");
}

function testBoldWrappedTitle(): void {
  expectMatch(
    "bold-wrapped title cleaned",
    parseTitleOnlyResponse("**feat: bump jest to 30**"),
    "feat: bump jest to 30",
  );
  expectMatch("double-bold edges cleaned", parseTitleOnlyResponse("****fix x****"), "fix x");
  expectMatch(
    "inner bold kept",
    parseTitleOnlyResponse("feat(scope): keep **core** intact"),
    "feat(scope): keep **core** intact",
  );
}

function testContentAfterBotBlockSurvives(): void {
  const input = "## Summary by CodeRabbit\n- bot bullets\n- more fill\n\n## Changes\nReal authored content follows.";
  const out = parseDescriptionOnlyResponse(input);
  expectIncludes("content after bot block survives", out, "Real authored content follows.");
  expectExcludes("bot heading removed", out, "CodeRabbit");
  expectExcludes("bot section bullets swallowed", out, "bot bullets");
  const suffix = "## Summary\nReal fix.\n\n## Summary by cubic\n- bot bullets\n\n## Testing\nRun the tests.";
  const outSuffix = parseDescriptionOnlyResponse(suffix);
  expectIncludes("content before bot block kept", outSuffix, "Real fix.");
  expectIncludes("content after bot block kept", outSuffix, "Run the tests.");
  expectExcludes("mid-document bot section removed", outSuffix, "bot bullets");
}

console.log("=== Parse / Bot-Signature Stripping Tests ===\n");
testCodeRabbitBlock();
testCubicAndMarkers();
testTemplatePreservation();
testTemplateWithBotAppendix();
testContentAfterBotBlockSurvives();
testRubberStampChecklist();
testCombinedParse();
testCopilotTrailers();
testAnchorGuard();
testBoldWrappedTitle();

const failures = getFailures();
if (failures > 0) {
  console.log(`\n❌ ${String(failures)} check(s) FAILED`);
  process.exit(1);
}
console.log("\n✅ All parse tests passed");
