import type { GenerateResponse } from "../types";

export function countDiffAnchors(text: string): number {
  return (text.match(/diffhunk:\/\//g) ?? []).length;
}

export interface ParseOptions {
  /** True when the prompt carried an Anchors section — a zero-anchor answer is suspicious then. */
  expectAnchors?: boolean;
}

function stripFences(text: string): string {
  return text.replace(/^```\w*\n?/, "").replace(/\n?```\s*$/, "");
}

function stripEdge(title: string, chars: string[]): string {
  let result = title;
  while (result.length > 0 && chars.includes(result[0] ?? "")) {
    result = result.substring(1);
  }
  while (result.length > 0 && chars.includes(result[result.length - 1] ?? "")) {
    result = result.substring(0, result.length - 1);
  }
  return result;
}

function cleanTitleText(title: string): string {
  let result = stripEdge(title, ['"', "'", "`"]);
  result = result.replace(/^#+\s*/, "");
  while (result.startsWith("**")) result = result.slice(2);
  while (result.endsWith("**")) result = result.slice(0, -2);
  result = result.replace(/^Title:\s*/i, "");
  return result.trim();
}

function stripBotSignatures(text: string): string {
  // Remove CodeRabbit sections (header + all content until next ## or end)
  let result = text.replace(/## Summary by CodeRabbit[\s\S]*/gim, "");
  // Remove cubic sections
  result = result.replace(/## Summary by cubic[\s\S]*/gim, "");
  // Remove copyberry markers
  result = result.replace(/<!-- copyberry-projection-id \d+ -->/g, "");
  // Remove badge lines
  result = result.replace(/^\[!\[badge\]\(https:\/\/img\.shields\.io\/.*\)\]\(https:\/\/example\.com\)$/gm, "");
  // Remove "Generated by" footers
  result = result.replace(/^Generated by CodeRabbit.*$/gim, "");
  // Remove stamped checklist lines from plain text (not in template contexts)
  // Heuristic: only remove if text has no ## headers (plain text context)
  const hasHeaders = /^## /m.test(result);
  if (!hasHeaders) {
    const lines = result.split("\n");
    const filtered = lines.filter((line) => {
      const trimmed = line.trim();
      if (/^[-*]\s*\[\s*x\s*\]\s+I tested my changes/i.test(trimmed)) return false;
      if (/^[-*]\s*\[\s*x\s*\]\s+Works on my machine/i.test(trimmed)) return false;
      return true;
    });
    result = filtered.join("\n");
  }
  // Remove "Automated Code Change" and similar
  result = result.replace(/^Automated Code Change.*$/gim, "");
  // Remove bot co-author trailers (Copilot)
  result = result.replace(/^Co-Authored-By: Copilot <.*>$/gim, "");
  // Remove "Overview:" pseudo-title lines
  result = result.replace(/^Overview:\s*.*$/gim, "");
  return result.trim();
}

function splitTitleAndDescription(cleaned: string): GenerateResponse {
  const doubleNewlineIdx = cleaned.indexOf("\n\n");
  if (doubleNewlineIdx !== -1) {
    return {
      title: cleaned.substring(0, doubleNewlineIdx).trim(),
      description: cleaned.substring(doubleNewlineIdx + 2).trim(),
    };
  }
  const firstNewlineIdx = cleaned.indexOf("\n");
  if (firstNewlineIdx !== -1) {
    return {
      title: cleaned.substring(0, firstNewlineIdx).trim(),
      description: cleaned.substring(firstNewlineIdx + 1).trim(),
    };
  }
  return { title: cleaned.trim(), description: "" };
}

export function parseCombinedResponse(text: string, _options?: ParseOptions): GenerateResponse {
  const cleaned = stripBotSignatures(text);
  const parsed = splitTitleAndDescription(stripFences(cleaned));
  let { title } = parsed;

  title = cleanTitleText(title);

  if (title.length > 100) {
    title = title.substring(0, 100).trim();
  }

  let description = parsed.description;
  description = description.replace(/^Title:.*\n?/i, "");
  return { title, description };
}

export function parseTitleOnlyResponse(text: string): string {
  const cleaned = stripBotSignatures(text);
  let title = cleanTitleText(stripFences(cleaned).trim());
  const newlineIdx = title.indexOf("\n");
  if (newlineIdx !== -1) {
    title = title.substring(0, newlineIdx).trim();
  }
  if (title.length > 100) {
    title = title.substring(0, 100).trim();
  }
  return title;
}

export function parseDescriptionOnlyResponse(text: string, _options?: ParseOptions): string {
  const cleaned = stripBotSignatures(text);
  let description = stripFences(cleaned).trim();
  description = description.replace(/^Title:.*\n?/i, "");
  const firstLine = description.split("\n")[0] || "";
  if (
    /^[^:]{1,50}:/i.test(firstLine) &&
    firstLine.length < 80 &&
    !firstLine.startsWith("#") &&
    !firstLine.startsWith("-") &&
    !firstLine.startsWith("*") &&
    !firstLine.includes("diffhunk://") &&
    !firstLine.includes("](")
  ) {
    description = description.substring(firstLine.length).trim();
  }
  return description;
}
